Cache = true
ExperienceTheFeatures = false
UseRegistry = true

[appearance]
color_mode = 0

[storage]
cache = true

[update]
url = "https://raw.githubusercontent.com/EECT/EECT_update/refs/heads/main/update.toml"
download_source = "0"
update_channel = "0"

[senior]
ExperienceTheFeatures = false
UseRegistry = true
