"1" = "我仍感叹于世界之大\n也沉醉于儿时情话\n不剩真假 不做挣扎 无谓笑话\n我终将青春还给了她\n连同指尖弹出的盛夏\n心之所动 就随风去了\n以爱之名 你还愿意吗"
"2" = "Take my hand now\nStay close to me\nBe my lover\nWon't you let me go\nclose your eyes now\nAnd you will see\nThere's a rainbow\nFor you and me"
"3" = "春めく季節に叫んだんだ\n僕は僕を恐れないと\n青春から全部奪ってったものを\n取り返しに行こう"
"4" = "你已经不是第一个看到这句话的人了"
"5" = "海内存知己，天涯若比邻。"
"6" = "要不要试试RinLit的Class Widgets？"
"7" = "我乃女神丽塔莉亚"
"8" = "你醒啦？\n是\n已经变成女孩子了"